title: "Soumyo Deep Gupta BASE"
description: "Welcome to my HomePage"
url: "https://d33p0st.in"

baseurl: "/"
permalink: /:title/

username: "tshoqr"
link: "https://instagram.com/tshoqr"

markdown: kramdown

plugins:
  - jekyll-feed
