title: d33p0st.in
description: Homepage of Soumyo Deep Gupta
show_downloads: true
google_analytics:
theme: jekyll-theme-merlot

# github:
#   zip_url: https://drive.google.com/uc?export=download&id=1W9mRZO2oA1PrULzJkRHDMiWNjIt_y6zT
#   view: https://drive.google.com/file/d/1W9mRZO2oA1PrULzJkRHDMiWNjIt_y6zT/view?usp=sharing